export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  subcategory?: string;
  categoryLabel: string;
  emoji: string;
  gradient: string;
  price: number; // قیمت فعلی به تومان
  originalPrice?: number; // قیمت اصلی (قبل از تخفیف)
  rating: number;
  reviews: number;
  isNew?: boolean;
  description: string;
};

/* دسته‌های محصول (سطح دوم نوبار) */
export const CATEGORIES: {
  slug: string;
  label: string;
  emoji: string;
}[] = [
  { slug: "lip", label: "آرایش لب", emoji: "💄" },
  { slug: "eye", label: "آرایش چشم", emoji: "👁" },
  { slug: "brow", label: "آرایش ابرو", emoji: "🖌" },
  { slug: "face", label: "آرایش صورت", emoji: "✨" },
  { slug: "body", label: "محصولات بهداشتی", emoji: "🧼" },
  { slug: "hair", label: "محصولات مو", emoji: "💇‍♀️" },
  { slug: "perfume", label: "عطر و اسپری", emoji: "🌸" },
  { slug: "accessory", label: "اکسسوری", emoji: "🎀" },
];

/* گروه‌های نوبار (سطح اول) — هر گروه یک یا چند دسته را پوشش می‌دهد */
export const CATEGORY_GROUPS: {
  slug: string;
  label: string;
  emoji: string;
  categories: string[];
}[] = [
  {
    slug: "cosmetic",
    label: "محصولات آرایشی",
    emoji: "💄",
    categories: ["face", "eye", "brow", "lip"],
  },
  {
    slug: "body",
    label: "محصولات بهداشتی",
    emoji: "🧼",
    categories: ["body"],
  },
  { slug: "hair", label: "محصولات مو", emoji: "💇‍♀️", categories: ["hair"] },
  {
    slug: "perfume",
    label: "عطر و اسپری",
    emoji: "🌸",
    categories: ["perfume"],
  },
  {
    slug: "accessory",
    label: "اکسسوری",
    emoji: "🎀",
    categories: ["accessory"],
  },
];

export function getCategoryGroup(slug?: string) {
  if (!slug) return undefined;
  return CATEGORY_GROUPS.find((g) => g.slug === slug);
}

/* گروهی که یک دسته به آن تعلق دارد (برای فعال نشان دادن چیپ گروه) */
export function groupOfCategory(category?: string) {
  if (!category) return undefined;
  return CATEGORY_GROUPS.find(
    (g) => g.slug === category || g.categories.includes(category),
  );
}

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "matte-lipstick-pecco",
    name: "رژ لب مات مخملی",
    brand: "پیکو",
    category: "lip",
    subcategory: "lipstick",
    categoryLabel: "آرایش لب",
    emoji: "💄",
    gradient: "from-rose-200 via-pink-200 to-fuchsia-100",
    price: 385000,
    originalPrice: 550000,
    rating: 4.8,
    reviews: 124,
    isNew: true,
    description:
      "رژ لب مات با بافت مخملی و ماندگاری بالا؛ رنگدانه‌های غنی و بدون حس خشکی روی لب. مناسب استفاده روزانه و مهمانی.",
  },
  {
    id: "p2",
    slug: "cherry-lip-tint",
    name: "تینت لب ماندگار چری",
    brand: "ولورا",
    category: "lip",
    subcategory: "tint-peeloff",
    categoryLabel: "آرایش لب",
    emoji: "🍒",
    gradient: "from-pink-300 via-rose-200 to-red-100",
    price: 245000,
    originalPrice: 290000,
    rating: 4.6,
    reviews: 89,
    description:
      "تینت سبک و ماندگار با رایحه گیلاس؛ لایه‌ای و قابل ساخت تا رنگ دلخواه، بدون چسبندگی.",
  },
  {
    id: "p3",
    slug: "sakura-eyeshadow-palette",
    name: "پالت سایه ساکورا ۱۲ رنگ",
    brand: "لومینر",
    category: "eye",
    subcategory: "eyeshadow",
    categoryLabel: "آرایش چشم",
    emoji: "🌸",
    gradient: "from-fuchsia-300 via-pink-200 to-violet-100",
    price: 620000,
    originalPrice: 890000,
    rating: 4.9,
    reviews: 210,
    isNew: true,
    description:
      "پالت ۱۲ رنگ با ترکیب مات و شایمر؛ رنگدانه‌های فوق‌العاده برای مدل‌های روزانه و عروس.",
  },
  {
    id: "p4",
    slug: "fluffy-volume-mascara",
    name: "ریمل حجم‌دهنده فرشته",
    brand: "لش بیوتی",
    category: "eye",
    subcategory: "mascara",
    categoryLabel: "آرایش چشم",
    emoji: "🖤",
    gradient: "from-slate-300 via-rose-100 to-pink-100",
    price: 340000,
    originalPrice: 425000,
    rating: 4.5,
    reviews: 97,
    description:
      "ریمل ضد آب با فرمول حجم‌دهنده و جداساز مژه؛ بدون ماسیده شدن در طول روز.",
  },
  {
    id: "p5",
    slug: "brow-pencil-viara",
    name: "مداد ابرو سه‌کاره",
    brand: "ویرا",
    category: "eye",
    subcategory: "eye-pencil",
    categoryLabel: "آرایش چشم",
    emoji: "✏️",
    gradient: "from-amber-200 via-rose-100 to-pink-100",
    price: 98000,
    rating: 4.3,
    reviews: 45,
    description:
      "مداد ابرو با برس و اسپولین؛ کشش نرم و رنگدهی یکنواخت برای فرم‌دهی ساده ابرو.",
  },
  {
    id: "p6",
    slug: "vitamin-c-serum",
    name: "سرم ویتامین C روشن‌کننده",
    brand: "گلدن اسکین",
    category: "body",
    subcategory: "face-care",
    categoryLabel: "مراقبت از صورت (اسکین کر)",
    emoji: "🍊",
    gradient: "from-orange-200 via-amber-100 to-rose-100",
    price: 780000,
    originalPrice: 1090000,
    rating: 4.9,
    reviews: 312,
    isNew: true,
    description:
      "سرم ضدلک با ۱۵٪ ویتامین C خالص؛ روشن‌کننده پوست، ضد چروک و مناسب انواع پوست.",
  },
  {
    id: "p7",
    slug: "spf50-sunscreen",
    name: "کرم ضدآفتاب SPF50 آبرسان",
    brand: "سانگارد",
    category: "body",
    subcategory: "face-care",
    categoryLabel: "مراقبت از صورت (اسکین کر)",
    emoji: "☀️",
    gradient: "from-yellow-200 via-rose-100 to-pink-100",
    price: 495000,
    originalPrice: 650000,
    rating: 4.8,
    reviews: 268,
    description:
      "ضدآفتاب بدون چربی با SPF50 و خاصیت آبرسانی؛ مناسب پوست‌های حساس، بدون سفید شدن.",
  },
  {
    id: "p8",
    slug: "aloe-sheet-mask",
    name: "ماسک ورقه‌ای آلوئه‌ورا",
    brand: "نچرال بایو",
    category: "body",
    subcategory: "face-care",
    categoryLabel: "مراقبت از صورت (اسکین کر)",
    emoji: "🥒",
    gradient: "from-green-200 via-emerald-100 to-rose-50",
    price: 89000,
    originalPrice: 145000,
    rating: 4.4,
    reviews: 156,
    description:
      "ماسک ورقه‌ای آبرسان با عصاره آلوئه‌ورا؛ پوست را شاداب و لطیف می‌کند.",
  },
  {
    id: "p9",
    slug: "contour-brush-set",
    name: "براش کانتور و هایلایتر",
    brand: "گلوری",
    category: "accessory",
    subcategory: "makeup-brush",
    categoryLabel: "براش و قلم‌مو",
    emoji: "🖌️",
    gradient: "from-violet-200 via-pink-100 to-rose-100",
    price: 185000,
    rating: 4.7,
    reviews: 74,
    description:
      "مجموعه دو براش حرفه‌ای با پرز نرم و متراکم برای سایه‌زنی و هایلایت دقیق.",
  },
  {
    id: "p10",
    slug: "24h-makeup-fixer",
    name: "اسپری فیکساتور ۲۴ ساعته",
    brand: "فیکس می",
    category: "face",
    subcategory: "fixing-spray",
    categoryLabel: "آرایش صورت",
    emoji: "💦",
    gradient: "from-sky-200 via-rose-100 to-fuchsia-100",
    price: 420000,
    originalPrice: 560000,
    rating: 4.6,
    reviews: 88,
    isNew: true,
    description:
      "فیکساتور سبک با ماندگاری ۲۴ ساعت؛ آرایش را در جای خود ثابت نگه می‌دارد و جلوی چربی را می‌گیرد.",
  },
  {
    id: "p11",
    slug: "matte-liquid-foundation",
    name: "کرم پودر مات ۲۴ ساعته",
    brand: "گلدن اسکین",
    category: "face",
    subcategory: "foundation",
    categoryLabel: "آرایش صورت",
    emoji: "🧴",
    gradient: "from-amber-100 via-rose-100 to-pink-100",
    price: 620000,
    originalPrice: 790000,
    rating: 4.7,
    reviews: 198,
    description:
      "کرم پودر مات با پوشانندگی متوسط تا کامل؛ ماندگاری بالا بدون حس سنگینی روی پوست.",
  },
  {
    id: "p12",
    slug: "creamy-concealer",
    name: "کانسیلر کرمی پوشانندگی بالا",
    brand: "ویرا",
    category: "face",
    subcategory: "concealer",
    categoryLabel: "آرایش صورت",
    emoji: "🫧",
    gradient: "from-orange-100 via-rose-100 to-pink-50",
    price: 210000,
    rating: 4.5,
    reviews: 87,
    description:
      "کانسیلر کرمی برای پوشش تیرگی زیر چشم و لک؛ بافت سبک و بدون جمعشدن در چین و چروک.",
  },
  {
    id: "p13",
    slug: "cream-blush",
    name: "رژگونه کرمی گلگون",
    brand: "لش بیوتی",
    category: "face",
    subcategory: "blush",
    categoryLabel: "آرایش صورت",
    emoji: "🍑",
    gradient: "from-pink-200 via-rose-100 to-orange-50",
    price: 265000,
    originalPrice: 330000,
    rating: 4.6,
    reviews: 112,
    description:
      "رژگونه کرمی با پخششدنی آسان و نت طبیعی گلودار؛ مناسب آرایش روزمره و مینیمال.",
  },
  {
    id: "p14",
    slug: "contour-sculpt-palette",
    name: "پالت کانتور و اسکالپت",
    brand: "لومینر",
    category: "face",
    subcategory: "contour",
    categoryLabel: "آرایش صورت",
    emoji: "🪄",
    gradient: "from-stone-200 via-rose-100 to-pink-50",
    price: 540000,
    rating: 4.7,
    reviews: 65,
    isNew: true,
    description:
      "پالت کانتور با تن‌های خنثی و گرم؛ برای سایهزنی استراتژیک و حجم‌دهی به فرم صورت.",
  },
  {
    id: "p15",
    slug: "liquid-highlighter",
    name: "هایلایتر مایع درخشش",
    brand: "فیکس می",
    category: "face",
    subcategory: "highlighter",
    categoryLabel: "آرایش صورت",
    emoji: "✨",
    gradient: "from-yellow-100 via-pink-100 to-rose-50",
    price: 295000,
    rating: 4.6,
    reviews: 93,
    description:
      "هایلایتر مایع با درخشش شیشه‌ای؛ قابل مخلوط با کرم پودر برای گلوی ملایم.",
  },
  {
    id: "p16",
    slug: "pressed-powder",
    name: "پودر فیکس پنکیک نیمه‌شفاف",
    brand: "پیکو",
    category: "face",
    subcategory: "powder-pancake",
    categoryLabel: "آرایش صورت",
    emoji: "☁️",
    gradient: "from-rose-100 via-pink-100 to-white",
    price: 380000,
    originalPrice: 450000,
    rating: 4.4,
    reviews: 71,
    description:
      "پنکیک فشرده نیمه‌شفاف برای تثبیت آرایش و کنترل براقی ناحیه T؛ همراه پاف و آینه.",
  },
  {
    id: "p17",
    slug: "hydrating-primer",
    name: "پرایمر آبرسان مات‌کننده",
    brand: "نچرال بایو",
    category: "face",
    subcategory: "primer",
    categoryLabel: "آرایش صورت",
    emoji: "💦",
    gradient: "from-sky-100 via-rose-100 to-pink-50",
    price: 340000,
    rating: 4.5,
    reviews: 58,
    description:
      "پرایمر آبرسان که منافذ را پر میکند و ماندگاری کرم پودر را چند برابر میکند.",
  },
  {
    id: "p18",
    slug: "liquid-eyeliner-matte",
    name: "خط چشم ماژیکی مشکی مات",
    brand: "ویرا",
    category: "eye",
    subcategory: "eyeliner",
    categoryLabel: "آرایش چشم",
    emoji: "🖋️",
    gradient: "from-slate-200 via-rose-100 to-pink-50",
    price: 195000,
    rating: 4.6,
    reviews: 143,
    description:
      "خط چشم نوک‌ظریف با جوهر مشکی مات؛ خط یکنواخت و ضد آب بدون پخششدگی.",
  },
  {
    id: "p19",
    slug: "half-lashes",
    name: "مژه مصنوعی نیمه‌ماهی",
    brand: "گلوری",
    category: "eye",
    subcategory: "false-lashes",
    categoryLabel: "آرایش چشم",
    emoji: "🦋",
    gradient: "from-fuchsia-100 via-rose-100 to-white",
    price: 145000,
    rating: 4.3,
    reviews: 39,
    description:
      "مژه مصنوعی نیمه‌ماهی سبک برای حالت طبیعی؛ مناسب چشم‌های گرد و باریک.",
  },
  {
    id: "p20",
    slug: "lash-serum",
    name: "سرم تقویت مژه و ابرو",
    brand: "گلدن اسکین",
    category: "eye",
    subcategory: "lash-growth",
    categoryLabel: "آرایش چشم",
    emoji: "🌿",
    gradient: "from-emerald-100 via-rose-100 to-pink-50",
    price: 480000,
    originalPrice: 590000,
    rating: 4.8,
    reviews: 176,
    isNew: true,
    description:
      "سرم تقویتی با پپتید برای بلندتر و پرپشتتر شدن مژهها؛ قابل استفاده روی ابرو.",
  },
  {
    id: "p21",
    slug: "tinted-brow-gel",
    name: "ژل ابرو تینت ماندگار",
    brand: "ویرا",
    category: "brow",
    subcategory: "brow-gel",
    categoryLabel: "آرایش ابرو",
    emoji: "💧",
    gradient: "from-amber-100 via-rose-100 to-pink-50",
    price: 165000,
    rating: 4.5,
    reviews: 64,
    description:
      "ژل ابرو تینتدار با برس مخصوص؛ پرپشتتر نشان دادن ابروها با ماندگاری تمام روز.",
  },
  {
    id: "p22",
    slug: "auto-brow-pencil",
    name: "مداد ابرو اتوماتیک میکرو",
    brand: "پیکو",
    category: "brow",
    subcategory: "brow-pencil-shadow",
    categoryLabel: "آرایش ابرو",
    emoji: "✏️",
    gradient: "from-stone-100 via-rose-100 to-pink-50",
    price: 120000,
    rating: 4.4,
    reviews: 88,
    description:
      "مداد ابرو نوک میکرو برای کشیدن تاربهتار موهای ابرو؛ همراه اسپولین و برس.",
  },
  {
    id: "p23",
    slug: "brow-wax",
    name: "واکس فرم‌ده ابرو",
    brand: "لش بیوتی",
    category: "brow",
    subcategory: "brow-grooming",
    categoryLabel: "آرایش ابرو",
    emoji: "🪒",
    gradient: "from-rose-100 via-pink-100 to-white",
    price: 135000,
    rating: 4.3,
    reviews: 47,
    description:
      "واکس شفاف فرم‌ده برای مهار موهای کج ابرو؛ همراه مینی برش برای مرتبسازی روزانه.",
  },
  {
    id: "p24",
    slug: "castor-brow-oil",
    name: "روغن تقویت ابرو کاستور",
    brand: "نچرال بایو",
    category: "brow",
    subcategory: "brow-growth",
    categoryLabel: "آرایش ابرو",
    emoji: "🌱",
    gradient: "from-lime-100 via-rose-100 to-pink-50",
    price: 175000,
    originalPrice: 220000,
    rating: 4.5,
    reviews: 55,
    description:
      "روغن کاستور خالص با قطرهچکان؛ تغذیه فولیکول ابرو برای رشد بهتر و پرپشتتر.",
  },
  {
    id: "p25",
    slug: "glass-lip-gloss",
    name: "لیپ گلاس براق شیشه‌ای",
    brand: "لومینر",
    category: "lip",
    subcategory: "lip-gloss-balm",
    categoryLabel: "آرایش لب",
    emoji: "💎",
    gradient: "from-pink-200 via-rose-100 to-white",
    price: 230000,
    rating: 4.5,
    reviews: 101,
    description:
      "لیپ گلاس با فینیش شیشه‌ای و غلظت متعادل؛ قابل استفاده تنهایی یا روی رژ.",
  },
  {
    id: "p26",
    slug: "rose-lip-balm",
    name: "بالم لب گل محمدی",
    brand: "نچرال بایو",
    category: "lip",
    subcategory: "lip-gloss-balm",
    categoryLabel: "آرایش لب",
    emoji: "💗",
    gradient: "from-rose-100 via-pink-100 to-white",
    price: 95000,
    rating: 4.7,
    reviews: 187,
    description:
      "بالم مغذی با عصاره گل محمدی و شی باتر؛ ترمیم لبهای خشک و ترکخورده.",
  },
  {
    id: "p27",
    slug: "creamy-lip-liner",
    name: "مداد لب کرمی مات",
    brand: "پیکو",
    category: "lip",
    subcategory: "lip-liner",
    categoryLabel: "آرایش لب",
    emoji: "🖍️",
    gradient: "from-red-100 via-pink-100 to-rose-50",
    price: 88000,
    rating: 4.4,
    reviews: 76,
    description:
      "مداد لب کرمی برای خطوط دقیق و جلوگیری از پخششدن رژ؛ تن‌های هماهنگ با رژها.",
  },
  {
    id: "p28",
    slug: "cooling-lip-plumper",
    name: "حجم‌دهنده لب خنک",
    brand: "فیکس می",
    category: "lip",
    subcategory: "lip-plumper",
    categoryLabel: "آرایش لب",
    emoji: "💋",
    gradient: "from-pink-200 via-fuchsia-100 to-rose-50",
    price: 255000,
    originalPrice: 320000,
    rating: 4.4,
    reviews: 69,
    isNew: true,
    description:
      "گلاس حجمدهنده با حس خنک و سوزن ملایم؛ حجم موقت لبها بدون تزریق.",
  },
  {
    id: "p29",
    slug: "razor-blades-set",
    name: "پک تیغ اصلاح صورت ۵ عددی",
    brand: "بست",
    category: "body",
    subcategory: "shaving",
    categoryLabel: "محصولات بهداشتی",
    emoji: "🪒",
    gradient: "from-sky-100 via-rose-100 to-white",
    price: 185000,
    rating: 4.4,
    reviews: 92,
    description:
      "تیغهای استیل ضدحساسیت با نوک ژله‌ای؛ اصلاح نرم و بدون بریدگی پوست.",
  },
  {
    id: "p30",
    slug: "sensitive-shaving-foam",
    name: "فوم اصلاح پوست حساس",
    brand: "بست",
    category: "body",
    subcategory: "shaving",
    categoryLabel: "محصولات بهداشتی",
    emoji: "🫧",
    gradient: "from-blue-100 via-rose-100 to-pink-50",
    price: 95000,
    rating: 4.3,
    reviews: 118,
    description:
      "فوم غلیظ با روغن نارگیل؛ لغزش تیغ را بهتر میکند و از قرمزی پوست جلوگیری میکند.",
  },
  {
    id: "p31",
    slug: "shea-body-lotion",
    name: "لوسیون بدن شی‌باتر",
    brand: "نچرال بایو",
    category: "body",
    subcategory: "body-care",
    categoryLabel: "محصولات بهداشتی",
    emoji: "🧴",
    gradient: "from-amber-100 via-pink-100 to-rose-50",
    price: 320000,
    originalPrice: 410000,
    rating: 4.6,
    reviews: 134,
    description:
      "لوسیون غنی با شی باتر و ویتامین E؛ آبرسان ۲۴ ساعته برای پوست بدن.",
  },
  {
    id: "p32",
    slug: "coffee-body-scrub",
    name: "اسکراب بدن قهوه و شکر",
    brand: "نچرال بایو",
    category: "body",
    subcategory: "body-care",
    categoryLabel: "محصولات بهداشتی",
    emoji: "☕",
    gradient: "from-orange-100 via-rose-100 to-pink-50",
    price: 265000,
    rating: 4.5,
    reviews: 88,
    description:
      "اسکراب لایهبردار با دانه قهوه؛ روشنکردن پوست و کاهش نمای سلولیت.",
  },
  {
    id: "p33",
    slug: "facial-cleansing-gel",
    name: "ژل شستشوی صورت",
    brand: "گلدن اسکین",
    category: "body",
    subcategory: "face-care",
    categoryLabel: "محصولات بهداشتی",
    emoji: "🧼",
    gradient: "from-teal-100 via-rose-100 to-pink-50",
    price: 240000,
    rating: 4.6,
    reviews: 156,
    description:
      "ژل شوینده با pH متعادل؛ پاکسازی عمیق آلودگی و آرایش بدون خشککردن پوست.",
  },
  {
    id: "p34",
    slug: "rose-face-mist",
    name: "میس آبرسان گل رز",
    brand: "نچرال بایو",
    category: "body",
    subcategory: "face-care",
    categoryLabel: "محصولات بهداشتی",
    emoji: "🌸",
    gradient: "from-rose-100 via-pink-100 to-white",
    price: 190000,
    originalPrice: 245000,
    rating: 4.5,
    reviews: 97,
    isNew: true,
    description:
      "اسپری آبرسان با عرق گل رز؛ خنککننده و تثبیتکننده آرایش در طول روز.",
  },
  {
    id: "p35",
    slug: "cleansing-cotton-pads",
    name: "پن پد پاکسازی ۱۰۰ عددی",
    brand: "سافت",
    category: "body",
    subcategory: "accessories",
    categoryLabel: "محصولات بهداشتی",
    emoji: "🧰",
    gradient: "from-slate-100 via-rose-100 to-white",
    price: 75000,
    rating: 4.4,
    reviews: 210,
    description:
      "پن پد دوطرفه با پنبه خالص؛ لطیف روی پوست و بدون پرزریزی.",
  },
  {
    id: "p36",
    slug: "argan-repair-shampoo",
    name: "شامپو تقویت‌کننده آرگان",
    brand: "لورآل",
    category: "hair",
    subcategory: "shampoo",
    categoryLabel: "محصولات مو",
    emoji: "🧴",
    gradient: "from-amber-100 via-rose-100 to-pink-50",
    price: 245000,
    originalPrice: 295000,
    rating: 4.7,
    reviews: 158,
    isNew: true,
    description:
      "شامپو بدون سولفات با روغن آرگان؛ تقویت‌کننده ساقه مو و مناسب موهای رنگ‌شده.",
  },
  {
    id: "p37",
    slug: "dry-hair-conditioner",
    name: "نرم‌کننده موی خشک",
    brand: "نیوآ",
    category: "hair",
    subcategory: "conditioner",
    categoryLabel: "محصولات مو",
    emoji: "🌾",
    gradient: "from-rose-100 via-pink-50 to-white",
    price: 185000,
    rating: 4.5,
    reviews: 92,
    description:
      "نرمکننده غنی با کره شی و روغن بادام؛ بازکننده گره مو بدون سنگین شدن.",
  },
  {
    id: "p38",
    slug: "keratin-hair-mask",
    name: "ماسک مو کراتینه",
    brand: "شوارتسکف",
    category: "hair",
    subcategory: "hair-mask",
    categoryLabel: "محصولات مو",
    emoji: "🥥",
    gradient: "from-fuchsia-100 via-rose-100 to-white",
    price: 320000,
    originalPrice: 395000,
    rating: 4.8,
    reviews: 143,
    description:
      "ماسک ترمیمکننده با کراتین و پروتئین ابریشم؛ درخشش و نرمی از اولین استفاده.",
  },
  {
    id: "p39",
    slug: "argan-hair-oil",
    name: "روغن آرگان مو",
    brand: "گلدن اسکین",
    category: "hair",
    subcategory: "hair-oil-serum",
    categoryLabel: "محصولات مو",
    emoji: "✨",
    gradient: "from-amber-100 via-rose-100 to-pink-50",
    price: 265000,
    rating: 4.6,
    reviews: 118,
    description:
      "روغن سبک بدون سیلیکون؛ محافظ حرارتی، ضد وز و براق‌کننده نوک مو.",
  },
  {
    id: "p40",
    slug: "heat-protect-hair-spray",
    name: "اسپری حالت‌دهنده حرارتی",
    brand: "اسنس",
    category: "hair",
    subcategory: "styling",
    categoryLabel: "محصولات مو",
    emoji: "🌬️",
    gradient: "from-sky-100 via-rose-100 to-pink-50",
    price: 195000,
    rating: 4.4,
    reviews: 76,
    isNew: true,
    description:
      "اسپری حالت‌دهنده با محافظ حرارتی تا ۲۳۰ درجه؛ حجم‌دهی و ثبات فر و صافی.",
  },
  {
    id: "p41",
    slug: "anti-hairloss-serum",
    name: "سرم ضد ریزش مو",
    brand: "ویشی",
    category: "hair",
    subcategory: "hair-oil-serum",
    categoryLabel: "محصولات مو",
    emoji: "🌿",
    gradient: "from-emerald-100 via-rose-100 to-pink-50",
    price: 540000,
    originalPrice: 640000,
    rating: 4.7,
    reviews: 201,
    description:
      "سرم تقویتی با کافئین و آمینوپپتید؛ کاهش ریزش و تقویت فولیکول‌های مو.",
  },
  {
    id: "p42",
    slug: "rose-nuit-perfume",
    name: "عطر زنانه رز نویر",
    brand: "لانکوم",
    category: "perfume",
    subcategory: "perfume",
    categoryLabel: "عطر و اسپری",
    emoji: "🌹",
    gradient: "from-rose-200 via-pink-100 to-white",
    price: 1850000,
    originalPrice: 2150000,
    rating: 4.9,
    reviews: 88,
    isNew: true,
    description:
      "عطر گلی-شرقی با رایحه رز دمشقی و مشک سفید؛ ماندگاری بالای ۸ ساعت.",
  },
  {
    id: "p43",
    slug: "woody-man-edp",
    name: "ادکلن مردانه وودی",
    brand: "دیور",
    category: "perfume",
    subcategory: "perfume",
    categoryLabel: "عطر و اسپری",
    emoji: "🌲",
    gradient: "from-slate-200 via-rose-100 to-pink-50",
    price: 1650000,
    rating: 4.7,
    reviews: 64,
    description:
      "ادوپرفیوم چوبی با نُت صندل، وتیور و فلفل سیاه؛ مناسب استفاده روزانه.",
  },
  {
    id: "p44",
    slug: "vanilla-body-splash",
    name: "بادی اسپلش وانیل",
    brand: "بادی‌شاپ",
    category: "perfume",
    subcategory: "body-splash",
    categoryLabel: "عطر و اسپری",
    emoji: "🍦",
    gradient: "from-amber-100 via-rose-100 to-white",
    price: 285000,
    rating: 4.5,
    reviews: 132,
    description:
      "بادی اسپلش شیرین وانیل و کارامل؛ سبک و مناسب تابستان، بدون الکل تند.",
  },
  {
    id: "p45",
    slug: "aloe-rollon-deodorant",
    name: "دئودورانت ضد تعریق",
    brand: "نیوآ",
    category: "perfume",
    subcategory: "deodorant",
    categoryLabel: "عطر و اسپری",
    emoji: "🌿",
    gradient: "from-emerald-100 via-rose-100 to-pink-50",
    price: 135000,
    rating: 4.4,
    reviews: 189,
    description:
      "رول‌آن ۴۸ ساعته با عصاره آلوئه‌ورا؛ بدون لکه سفید و مناسب پوست حساس.",
  },
  {
    id: "p46",
    slug: "makeup-brush-set",
    name: "ست براش آرایشی ۱۲ عددی",
    brand: "بیوتی آرت",
    category: "accessory",
    subcategory: "makeup-brush",
    categoryLabel: "اکسسوری",
    emoji: "🖌️",
    gradient: "from-fuchsia-100 via-rose-100 to-white",
    price: 620000,
    originalPrice: 780000,
    rating: 4.8,
    reviews: 97,
    isNew: true,
    description:
      "ست براش با موی مصنوعی نرم و دسته ارگونومیک؛ شامل براش صورت، چشم و لب.",
  },
  {
    id: "p47",
    slug: "soft-makeup-sponge",
    name: "اسفنج آرایشی نرم",
    brand: "بیوتی آرت",
    category: "accessory",
    subcategory: "sponge-puff",
    categoryLabel: "اکسسوری",
    emoji: "🧽",
    gradient: "from-rose-100 via-pink-50 to-white",
    price: 85000,
    rating: 4.6,
    reviews: 244,
    description:
      "اسفنج لاتکس‌فری با بافت مخملی؛ پخش یکنواخت کرم پودر به‌صورت خشک و مرطوب.",
  },
  {
    id: "p48",
    slug: "pro-eyelash-curler",
    name: "فر مژه حرفه‌ای",
    brand: "گلوری",
    category: "accessory",
    subcategory: "eyelash-curler",
    categoryLabel: "اکسسوری",
    emoji: "👁️",
    gradient: "from-slate-100 via-rose-100 to-pink-50",
    price: 120000,
    rating: 4.5,
    reviews: 68,
    description:
      "فر مژه با پد سیلیکونی و فنر نرم؛ حالت‌دهی سریع و بدون شکستگی مژه.",
  },
  {
    id: "p49",
    slug: "makeup-organizer-bag",
    name: "کیف لوازم آرایش",
    brand: "سافت",
    category: "accessory",
    subcategory: "organizer",
    categoryLabel: "اکسسوری",
    emoji: "🎀",
    gradient: "from-pink-100 via-rose-100 to-white",
    price: 240000,
    rating: 4.3,
    reviews: 51,
    description:
      "کیف آرایشی با چند جیب و آستر ضدآب؛ نگهداری مرتب براش‌ها و لوازم کوچک.",
  },
  {
    id: "p50",
    slug: "desktop-vanity-mirror",
    name: "آینه رومیزی دوطرفه",
    brand: "سافت",
    category: "accessory",
    subcategory: "mirror",
    categoryLabel: "اکسسوری",
    emoji: "🪞",
    gradient: "from-violet-100 via-rose-100 to-pink-50",
    price: 380000,
    originalPrice: 450000,
    rating: 4.6,
    reviews: 43,
    description:
      "آینه رومیزی دوطرفه با بزرگنمایی ۵ برابر؛ پایه چرخان و مناسب میز آرایش.",
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function productsByCategory(category?: string, sub?: string): Product[] {
  // بدون دسته: همه محصولات (یا فیلتر فقط بر اساس زیردسته)
  if (!category) {
    return sub ? PRODUCTS.filter((p) => p.subcategory === sub) : PRODUCTS;
  }

  // گروه (مثلاً محصولات آرایشی = صورت + چشم + ابرو + لب)
  const group = getCategoryGroup(category);
  if (group) {
    let list = PRODUCTS.filter((p) => group.categories.includes(p.category));
    if (sub) {
      list = list.filter(
        (p) => p.category === sub || p.subcategory === sub,
      );
    }
    return list;
  }

  // دسته تکی
  let list = PRODUCTS.filter((p) => p.category === category);
  if (sub) list = list.filter((p) => p.subcategory === sub);
  return list;
}

export const NEW_PRODUCTS = PRODUCTS.filter((p) => p.isNew);

export const DEALS = PRODUCTS.filter((p) => p.originalPrice);